/*
 * generated by Xtext
 */
package org.mod4j.dsl.presentation.xtext;

/**
 * Use this class to register components to be used within the IDE.
 */
public class PresentationRuntimeModule extends org.mod4j.dsl.presentation.xtext.AbstractPresentationRuntimeModule {

}
