/**
 * Extension Point initial generated at: Wed Jun 18 08:52:21 CEST 2008
 */
package org.company.recordshop.domain;

/**
 * 
 *
 * @author Generated by Mod4j BusinessDomain DSL
 */
public class OrderLine extends OrderLineImplBase {

	/**
	 * Default no-argument constructor for OrderLine 
	 */
	protected OrderLine() {

	}

	/**
	 * Minimal constructor for OrderLine
	 * @param lineNumber (integer) 
	 * @param description (string) 
	 * @param lineAmount (decimal) 
	 */
	public OrderLine(int lineNumber, String description, float lineAmount) {
		super(lineNumber, description, lineAmount);
	}

}
