
/**
 * Extension point generated initially by Mod4j BusinessDomain DSL by BeanClassExtensionPoint in NewJavaBean.xpt at: Fri Mar 13 10:00:49 CET 2009
 */
package org.company.recordshop.domain;

/**
 * This class has no meaning in the recordshop application. Its purpose is to test
uni-directional many-to-many associations
 *
 * @author Generated by Mod4j BusinessDomain DSL
 */
public class Many2ManyTo extends Many2ManyToImplBase {

	/**
	 * Default no-argument constructor for Many2ManyTo 
	 */
	protected Many2ManyTo() {

	}

	/**
	 * Minimal constructor for Many2ManyTo
	 * @param property (String) 
	 */
	public Many2ManyTo(String property) {
		super(property);
	}

}
