
/**
 * Extension point generated initially by Mod4j BusinessDomain DSL by BeanClassExtensionPoint in NewJavaBean.xpt at: Fri Mar 13 10:00:49 CET 2009
 */
package org.company.recordshop.domain;

/**
 * This class has no meaning in the recordshop application. Its purpose is to test
ordered one-to-many associations
 *
 * @author Generated by Mod4j BusinessDomain DSL
 */
public class One2ManyOrderedTo extends One2ManyOrderedToImplBase {

	/**
	 * Default no-argument constructor for One2ManyOrderedTo 
	 */
	protected One2ManyOrderedTo() {

	}

	/**
	 * Minimal constructor for One2ManyOrderedTo
	 * @param property (String) 
	 */
	public One2ManyOrderedTo(String property) {
		super(property);
	}

}
