
/**
 * Extension point generated initially by Mod4j BusinessDomain DSL by BeanClassExtensionPoint in NewJavaBean.xpt at: Fri Mar 13 10:00:53 CET 2009
 */
package org.company.recordshop.domain;

/**
 * 
 *
 * @author Generated by Mod4j BusinessDomain DSL
 */
public class OrderLine extends OrderLineImplBase {

	/**
	 * Default no-argument constructor for OrderLine 
	 */
	protected OrderLine() {

	}

	/**
	 * Minimal constructor for OrderLine
	 * @param lineNumber (int) 
	 * @param description (String) 
	 * @param lineAmount (float) 
	 */
	public OrderLine(int lineNumber, String description, float lineAmount) {
		super(lineNumber, description, lineAmount);
	}

}
