
/*
 * generated by Xtext
 */
package org.mod4j.dsl.presentation.xtext;

import org.eclipse.xtext.ui.common.service.UIPluginModule;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.mod4j.eclipse.builder.Mod4jBuilder;
import org.osgi.framework.BundleContext;

import com.google.inject.Guice;
import com.google.inject.Injector;

import java.util.Map;
import java.util.HashMap;

/**
 * Generated
 */
public class Mod4jPresentationActivator extends AbstractUIPlugin {

	private Map<String,Injector> injectors = new HashMap<String,Injector>();
	private static Mod4jPresentationActivator INSTANCE;

	public Injector getInjector(String languageName) {
		return injectors.get(languageName);
	}
	
	@Override
	public void start(BundleContext context) throws Exception {
		super.start(context);
		INSTANCE = this;
		
		injectors.put("org.mod4j.dsl.presentation.xtext.Presentation", Guice.createInjector(
			new org.mod4j.dsl.presentation.xtext.PresentationUiModule(),
			createUIPluginModule()
		));
        crossx();
		
	}
	
	public static Mod4jPresentationActivator getInstance() {
		return INSTANCE;
	}
	
	protected UIPluginModule createUIPluginModule() {
		return new UIPluginModule(this);
	}

    protected void crossx() {
        System.err.println("PresentationDslEditor.refreshPluginActions");
        Mod4jBuilder.initCrossx("PresentationDslEditorPlugin"); 
    }

}
