
/**
 * DO NOT MODIFY THIS FILE, CHANGES WILL BE AUTOMATICALLY OVERWRITTEN 
 *
 * Generated by Mod4j BusinessDomain DSL by BeanClassQueryExample in QueryExample.xpt at: Thu Apr 02 14:32:55 CEST 2009
 */
package com.rosa.breakfast.domain;

/**
 * A subclass of StandardBreakfast to be used as example object
 * in Query-by-Example (QBE) queries. It turns off validation in the
 * no-argument constructor.
 *
 * @author Generated by Mod4j BusinessDomain DSL
 */
public final class StandardBreakfastExample extends StandardBreakfast {

	public StandardBreakfastExample() {
		activateValidation(false);
	}
}
