/**
 * Initially generated by Mod4j at Thu Feb 19 09:02:33 CET 2009
 */
package org.company.recordshop.data.spring.dao;

/**
 * Many2ManyTo Data Access Object (DOA) Implementation. Responsible for Creating,
 * Reading, Updating and Deleting Many2ManyTo objects in the database. All database
 * access is done here.
 *  
 * @author Initially generated by Mod4j
 */
public class Many2ManyToDaoImpl extends Many2ManyToDaoImplBase
		implements
			Many2ManyToDao {

}
