/**
 * Initially generated by Mod4j at Thu Feb 19 09:20:24 CET 2009
 */
package org.company.recordshop.data.spring.dao;

/**
 * One2ManyFrom Data Access Object (DOA) Implementation. Responsible for Creating,
 * Reading, Updating and Deleting One2ManyFrom objects in the database. All database
 * access is done here.
 *  
 * @author Initially generated by Mod4j
 */
public class One2ManyFromDaoImpl extends One2ManyFromDaoImplBase
		implements
			One2ManyFromDao {

}
