/**
 * Initially generated by Mod4j at Thu Feb 19 09:20:24 CET 2009
 */
package org.company.recordshop.data.spring.dao;

/**
 * One2ManyOrderedTo Data Access Object (DOA) Implementation. Responsible for Creating,
 * Reading, Updating and Deleting One2ManyOrderedTo objects in the database. All database
 * access is done here.
 *  
 * @author Initially generated by Mod4j
 */
public class One2ManyOrderedToDaoImpl extends One2ManyOrderedToDaoImplBase
		implements
			One2ManyOrderedToDao {

}
