/**
 * Initial generated by Mod4j at Wed Nov 12 23:30:36 CET 2008
 */
package org.company.recordshop.data.spring.dao;

/**
 * Order Data Access Object (DOA) Implementation. Responsible for Creating,
 * Reading, Updating and Deleting Order objects in the database. All database
 * access is done here.
 *  
 * @author Initial generated by Mod4j
 */
public class OrderDaoImpl extends OrderDaoImplBase implements OrderDao {

	// TODO: Add manual DAO method implementations here
}
