/**
 * Initial generated by Mod4j at Wed Aug 27 09:30:13 CEST 2008
 */
package org.company.recordshop.data.spring.dao;

/**
 * OrderLine Data Access Object (DOA) Implementation. Responsible for Creating,
 * Reading, Updating and Deleting OrderLine objects in the database. All database
 * access is done here.
 *  
 * @author Initial generated by Mod4j
 */
public class OrderLineDaoImpl extends OrderLineDaoImplBase
		implements
			OrderLineDao {

	// TODO: Add manual DAO method implementations here
}
