/**
 * Initially generated by Mod4j at Wed Nov 12 23:30:36 CET 2008
 */
package org.company.recordshop.data.spring.dao;

/**
 * Record Data Access Object (DOA) Implementation. Responsible for Creating,
 * Reading, Updating and Deleting Record objects in the database. All database
 * access is done here.
 *  
 * @author Initially generated by Mod4j
 */
public class RecordDaoImpl extends RecordDaoImplBase implements RecordDao {

	// TODO: Add manual DAO method implementations here
}
