
/**
 * Extension point, initially generated by Mod4j. 
 *     Time             : Sun Jun 06 16:43:54 CEST 2010
 *     Application model: Child
 *     Generator        :  Mod4j BusinessDomainDsl generator: DaoImpl.xpt
 *
 * It is intended to customize and maintain this file by hand. 
 * If you remove this file, it will be regenerated by Mod4j to its original state.
 */

package org.company.recordshop.data;

/**
 * ChildDao Data Access Object (DAO). Responsible for accessing the database.
 *
 * This interface is intended to be manually changed by developers. 
 * 
 * @author Initially generated by Mod4j
 * 
 */
public interface ChildDao extends ChildDaoBase {
}
