/*
* generated by Xtext
*/
package org.mod4j.dsl.presentation.xtext.parser.antlr;

import org.antlr.runtime.ANTLRInputStream;
import org.eclipse.xtext.parser.antlr.ITokenDefProvider;
import org.eclipse.xtext.parser.IParseResult;
import org.eclipse.xtext.parser.ParseException;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

import com.google.inject.Inject;

import org.mod4j.dsl.presentation.xtext.services.PresentationGrammarAccess;

public class PresentationParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject 
    protected ITokenDefProvider antlrTokenDefProvider;
	
	@Inject
	private PresentationGrammarAccess grammarAccess;
	
	@Override
	protected IParseResult parse(String ruleName, ANTLRInputStream in) {
		org.mod4j.dsl.presentation.xtext.parser.antlr.internal.InternalPresentationLexer lexer = new org.mod4j.dsl.presentation.xtext.parser.antlr.internal.InternalPresentationLexer(in);
		XtextTokenStream stream = new XtextTokenStream(lexer, antlrTokenDefProvider);
		stream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
		org.mod4j.dsl.presentation.xtext.parser.antlr.internal.InternalPresentationParser parser = new org.mod4j.dsl.presentation.xtext.parser.antlr.internal.InternalPresentationParser(
				stream, getElementFactory(), grammarAccess);
		parser.setTokenTypeMap(antlrTokenDefProvider.getTokenDefMap());
		try {
			if(ruleName != null)
				return parser.parse(ruleName);
			return parser.parse();
		} catch (Exception re) {
			throw new ParseException(re.getMessage(),re);
		}
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "PresentationModel";
	}
	
	public PresentationGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(PresentationGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
