
/**
 * Extension point, initially generated by Mod4j. 
 *     Time             : Sat Sep 18 17:57:45 CEST 2010
 *     Application model: Owner
 *     Generator        :  Mod4j BusinessDomainDsl generator: DaoImpl.xpt
 *
 * It is intended to customize and maintain this file by hand. 
 * If you remove this file, it will be regenerated by Mod4j to its original state.
 */

package org.company.recordshop.data.hibernate.spring;

import org.company.recordshop.data.OwnerDao;

/**
 * Owner Data Access Object (DAO) Implementation. Responsible for Creating,
 * Reading, Updating and Deleting Owner objects in the database.
 * All database access is done here.
 *  
 * @author Initially generated by Mod4j
 */
public class OwnerDaoImpl extends OwnerDaoImplBase implements OwnerDao {

}
