/**
 * Extension point generated initially by Mod4j BusinessDomain DSL by BeanClassExtensionPoint in JavaBean.xpt at: Tue Feb 24 11:25:10 CET 2009
 */
package org.company.recordshop.domain;

import org.joda.time.DateTime;

/**
 * An artist is a Person who has had a role in producing a Record
 *
 * @author Generated by Mod4j BusinessDomain DSL
 */
public class Artist extends ArtistImplBase {

	/**
	 * Default no-argument constructor for Artist 
	 */
	protected Artist() {
		super();
	}

	/**
	 * Minimal constructor for Artist
	 * @param firstName (String) First name of the person.
	 * @param lastName (String) Last name of the person.
	 * @param birthDate (DateTime) 
	 * @param artistName (String) 
	 */
	public Artist(String firstName, String lastName, DateTime birthDate,
			String artistName) {
		super(firstName, lastName, birthDate, artistName);
	}

}
