
/**
 * Extension point, initially generated by Mod4j. 
 *     Time             : Sat Sep 18 17:57:45 CEST 2010
 *     Application model: Biker
 *     Generator        :  Mod4j BusinessDomainDsl generator: NewJavaBean.xpt
 *
 * It is intended to customize and maintain this file by hand. 
 * If you remove this file, it will be regenerated by Mod4j to its original state.
 */

package org.company.recordshop.domain;

/**
 * 
 *
 * @author Generated by Mod4j BusinessDomain DSL
 */
public class Biker extends BikerImplBase {

	/**
	 * Default no-argument constructor for Biker
	 */
	protected Biker() {

	}

	/**
	 * Minimal constructor for Biker
	 * @param name (String) 
	 */
	public Biker(String name) {
		super(name);
	}

	/**
	 * Creates a Biker with the specified ID.
	 */
	protected Biker(Long id) {
		super(id);
	}

}
