
/**
 * Extension point generated initially by Mod4j BusinessDomain DSL by BeanClassExtensionPoint in NewJavaBean.xpt at: Fri Mar 13 10:00:49 CET 2009
 */
package org.company.recordshop.domain;

import org.joda.time.DateTime;

/**
 * Test derived attributes
 *
 * @author Generated by Mod4j BusinessDomain DSL
 */
public class DerivedNotYetImplemented extends DerivedNotYetImplementedImplBase {

	/**
	 * Minimal constructor for DerivedNotYetImplemented
	 */
	public DerivedNotYetImplemented(

	) {
		super(

		);
	}

	/**
	 * @return first (String) 
	 */
	public String getFirst() {
		throw new UnsupportedOperationException("Not implemented");
	}

	/**
	 *
	 * @return secondo (boolean) 
	 */
	public boolean isSecondo() {
		throw new UnsupportedOperationException("Not implemented");
	}

	/**
	 * @return third (DateTime) 
	 */
	public DateTime getThird() {
		throw new UnsupportedOperationException("Not implemented");
	}

	/**
	 * @return fourth (int) 
	 */
	public int getFourth() {
		throw new UnsupportedOperationException("Not implemented");
	}

	/**
	 * @return fifth (float) 
	 */
	public float getFifth() {
		throw new UnsupportedOperationException("Not implemented");
	}

	/**
	 * @param first (String) 
	 */
	public void setFirst(final String first) {
		throw new UnsupportedOperationException("Not implemented");
	}

	/**
	 * @param secondo (boolean) 
	 */
	public void setSecondo(final boolean secondo) {
		throw new UnsupportedOperationException("Not implemented");
	}

	/**
	 * @param third (DateTime) 
	 */
	public void setThird(final DateTime third) {
		throw new UnsupportedOperationException("Not implemented");
	}

	/**
	 * @param fourth (int) 
	 */
	public void setFourth(final int fourth) {
		throw new UnsupportedOperationException("Not implemented");
	}

	/**
	 * @param fifth (float) 
	 */
	public void setFifth(final float fifth) {
		throw new UnsupportedOperationException("Not implemented");
	}

}
