
/**
 * Extension point, initially generated by Mod4j. 
 *     Time             : Sun Jun 06 16:43:54 CEST 2010
 *     Application model: GrandChild
 *     Generator        :  Mod4j BusinessDomainDsl generator: NewJavaBean.xpt
 *
 * It is intended to customize and maintain this file by hand. 
 * If you remove this file, it will be regenerated by Mod4j to its original state.
 */

package org.company.recordshop.domain;

/**
 * 
 *
 * @author Generated by Mod4j BusinessDomain DSL
 */
public class GrandChild extends GrandChildImplBase {

	/**
	 * Default no-argument constructor for GrandChild 
	 */
	protected GrandChild() {

	}

	/**
	 * Minimal constructor for GrandChild
	 * @param name (String) 
	 */
	public GrandChild(String name) {
		super(name);
	}

    protected GrandChild(Long id) {
        super(id);
    }

}
