/**
 * Extension point generated initially by Mod4j BusinessDomain DSL by BeanClassExtensionPoint in JavaBean.xpt at: Thu Feb 19 13:22:59 CET 2009
 */
package org.company.recordshop.domain;

/**
 * This class has no meaning in the recordshop application. Its purpose is to test
ordered one-to-many associations
 *
 * @author Generated by Mod4j BusinessDomain DSL
 */
public class Many2ManyOrderedTo extends Many2ManyOrderedToImplBase {

	/**
	 * Default no-argument constructor for Many2ManyOrderedTo 
	 */
	protected Many2ManyOrderedTo() {

	}

	/**
	 * Minimal constructor for Many2ManyOrderedTo
	 * @param property (string) 
	 */
	public Many2ManyOrderedTo(String property) {
		super(property);
	}

}
