/**
 * Extension point generated initially by Mod4j BusinessDomain DSL by BeanClassExtensionPoint in JavaBean.xpt at: Thu Feb 19 09:02:32 CET 2009
 */
package org.company.recordshop.domain;

/**
 * 
 *
 * @author Generated by Mod4j BusinessDomain DSL
 */
public class Many2ManyTo extends Many2ManyToImplBase {

	/**
	 * Default no-argument constructor for Many2ManyTo 
	 */
	protected Many2ManyTo() {

	}

	/**
	 * Minimal constructor for Many2ManyTo
	 * @param property (string) 
	 */
	public Many2ManyTo(String property) {
		super(property);
	}

}
