/**
 * Extension point generated initially by Mod4j BusinessDomain DSL by BeanClassExtensionPoint in JavaBean.xpt at: Thu Feb 19 09:20:24 CET 2009
 */
package org.company.recordshop.domain;

/**
 * This class has no meaning in the recordshop application. Its purpose is to test
ordered one-to-many associations
 *
 * @author Generated by Mod4j BusinessDomain DSL
 */
public class One2ManyFrom extends One2ManyFromImplBase {

	/**
	 * Default no-argument constructor for One2ManyFrom 
	 */
	protected One2ManyFrom() {

	}

	/**
	 * Minimal constructor for One2ManyFrom
	 * @param property (string) 
	 */
	public One2ManyFrom(String property) {
		super(property);
	}

}
