/**
 * Extension point generated initially by Mod4j BusinessDomain DSL by BeanClassExtensionPoint in JavaBean.xpt at: Tue Feb 24 16:48:45 CET 2009
 */
package org.company.recordshop.domain;

/**
 * This class has no meaning in the recordshop application. Its purpose is to test ordered one-to-many associations
 * 
 * @author Generated by Mod4j BusinessDomain DSL
 */
public class One2ManyFrom extends One2ManyFromImplBase {

    /**
     * Default no-argument constructor for One2ManyFrom
     */
    protected One2ManyFrom() {

    }

    /**
     * Minimal constructor for One2ManyFrom
     * 
     * @param property
     *            (String)
     */
    public One2ManyFrom(String property) {
        super(property);
    }

    /**
     * @param index
     * @return
     */
    /**
     * @param index
     *            blablabla
     * @return blablabla
     * @throws IndexOutOfBoundsException
     *             if the index is out of range (index < 0 || index >= size()).
     */
    public One2ManyOrderedTo remove(int index) throws UnsupportedOperationException, IndexOutOfBoundsException {
        return new One2ManyOrderedTo();
    }
}
