/**
 * Extension point generated initially by Mod4j BusinessDomain DSL by BeanClassExtensionPoint in JavaBean.xpt at: Tue Feb 24 16:48:48 CET 2009
 */
package org.company.recordshop.domain;

import org.joda.time.DateTime;

/**
 * An Order represents the agreement between a Customer and the RecordShop about one or more purchased Records.
 *
 * @author Generated by Mod4j BusinessDomain DSL
 */
public class Order extends OrderImplBase {

	/**
	 * Default no-argument constructor for Order 
	 */
	protected Order() {

	}

	/**
	 * Minimal constructor for Order
	 * @param orderNumber (String) A number to identify the Order
	 */
	public Order(String orderNumber) {
		super(orderNumber);
	}

}
