
/**
 * Extension point generated initially by Mod4j BusinessDomain DSL by BeanClassExtensionPoint in NewJavaBean.xpt at: Fri Mar 13 10:00:52 CET 2009
 */
package org.company.recordshop.domain;

/**
 * A Record is a representation of a physical medium containing one or more musical compositions.
 *
 * @author Generated by Mod4j BusinessDomain DSL
 */
public class Record extends RecordImplBase {

	/**
	 * Default no-argument constructor for Record 
	 */
	protected Record() {

	}

	/**
	 * Minimal constructor for Record
	 * @param asin (String) 
	 * @param price (float) 
	 * @param type (RecordTypeEnum) 
	 */
	public Record(String asin, float price, RecordTypeEnum type) {
		super(asin, price, type);
	}

}
