
/** 
 * Initially generated by Mod4j at Wed Apr 08 11:05:51 CEST 2009
 */
package com.rosa.breakfast.data;

/**
 * AddressDao Data Access Object (DAO). Responsible for accessing the database.
 *
 * This interface is intended to be manually changed by developers. 
 * 
 * @author Initially generated by Mod4j
 * 
 */
public interface AddressDao extends AddressDaoBase {

}
