
/** 
 * Initially generated by Mod4j at Wed Apr 08 15:33:14 CEST 2009
 */
package com.rosa.breakfast.data;

/**
 * BreakfastDao Data Access Object (DAO). Responsible for accessing the database.
 *
 * This interface is intended to be manually changed by developers. 
 * 
 * @author Initially generated by Mod4j
 * 
 */
public interface BreakfastDao extends BreakfastDaoBase {
	
}
