
/** 
 * Initially generated by Mod4j at Mon Jun 15 11:35:02 CEST 2009
 */
package com.rosa.breakfast.data;

/**
 * StandardBreakfastDao Data Access Object (DAO). Responsible for accessing the database.
 *
 * This interface is intended to be manually changed by developers. 
 * 
 * @author Initially generated by Mod4j
 * 
 */
public interface StandardBreakfastDao extends StandardBreakfastDaoBase {
}
