
/**
 * DO NOT MODIFY THIS FILE, CHANGES WILL BE AUTOMATICALLY OVERWRITTEN 
 *
 * Generated by Mod4j DataContract DSL, BusinessClassDto in dtoBean.xpt at: Fri Apr 03 14:19:48 CEST 2009
 */
package com.rosa.breakfast.web.dto;

import java.io.Serializable;

/**
 * 
 *
 * @author generated by Mod4j
 */
@SuppressWarnings("serial")
public class PartDto implements Serializable {

	/**
	 *  id: The identifier of this object.
	 */
	private Long id;

	/**
	 *  quantity: 
	 */
	private Integer quantity;

	/**
	 *  ComestibleDto: 
	 */
	private ComestibleDto comestible = null;

	/**
	 * Default no-argument constructor for PartDto 
	 */
	public PartDto() {
		super();
	}

	/**
	 *
	 * @return id (Long) The identifier of this object.
	 */
	public Long getId() {
		return this.id;
	}
	/**
	 *
	 * @param id (Long) The identifier of this object.
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 *
	 * @return quantity (Integer) 
	 */
	public Integer getQuantity() {
		return this.quantity;
	}

	/**
	 * @param quantity (Integer) 
	 */
	public void setQuantity(final Integer quantity) {
		this.quantity = quantity;
	}

	/**
	 * @return ComestibleDto (ComestibleDto) 
	 */
	public ComestibleDto getComestible() {
		return this.comestible;
	}

	/**  
	 * @param comestible (ComestibleDto) 
	 */
	public void setComestible(final ComestibleDto comestible) {
		this.comestible = comestible;
	}

}
