/** 
 * Initially generated by Mod4j at Wed Nov 12 23:30:36 CET 2008
 */
package org.company.recordshop.data.spring.dao;

/**
 * PersonDao Data Access Object (DAO). Responsible for accessing the database.
 *
 * This interface is intended to be manually changed by developers. 
 * 
 * @author Initially generated by Mod4j
 * 
 */
public interface PersonDao extends PersonDaoBase {

	// TODO: Add manual DAO methods over here
}
