/**
 * Initially generated by Mod4j at Tue Feb 10 13:55:28 CET 2009
 */
package org.company.recordshop.data.spring.dao;

/**
 * Record Data Access Object (DOA) Implementation. Responsible for Creating,
 * Reading, Updating and Deleting Record objects in the database. All database
 * access is done here.
 *  
 * @author Initially generated by Mod4j
 */
public class RecordDaoImpl extends RecordDaoImplBase implements RecordDao {

}
