
/**
 * Extension point generated initially by Mod4j BusinessDomain DSL by BeanClassExtensionPoint in NewJavaBean.xpt at: Wed Apr 08 14:20:52 CEST 2009
 */
package com.rosa.breakfast.domain;

/**
 * 
 *
 * @author Generated by Mod4j BusinessDomain DSL
 */
public class Address extends AddressImplBase {

	/**
	 * Default no-argument constructor for Address 
	 */
	protected Address() {
	}

	/**
	 * Minimal constructor for Address
	 * @param street (String) 
	 * @param number (String) 
	 */
	public Address(String street, String number) {
		super(street, number);
	}

}
