
/**
 * Extension point generated initially by Mod4j BusinessDomain DSL by BeanClassExtensionPoint in NewJavaBean.xpt at: Wed Apr 08 06:50:05 CEST 2009
 */
package com.rosa.breakfast.domain;

/**
 * 
 *
 * @author Generated by Mod4j BusinessDomain DSL
 */
public class Customer extends CustomerImplBase {

	/**
	 * Default no-argument constructor for Customer 
	 */
	protected Customer() {

	}

	/**
	 * Minimal constructor for Customer
	 * @param accountNumber (int) 
	 */
	public Customer(int accountNumber) {
		super(accountNumber);
	}

}
