/**
 * Extension point generated initially by Mod4j BusinessDomain DSL by BeanClassExtensionPoint in NewJavaBean.xpt at: Wed Apr 01 21:03:34 CEST 2009
 */
package com.rosa.breakfast.domain;

import org.mod4j.runtime.validation.NotNullValidator;

import com.rosa.breakfast.domain.businessrules.PartCheckMinimumQuantity;

/**
 * 
 * 
 * @author Generated by Mod4j BusinessDomain DSL
 */
public class Part extends PartImplBase {

    private static final long serialVersionUID = 1L;

    /**
     * Default no-argument constructor for Part
     */
    protected Part() {
        validation.addValidator(new NotNullValidator(Part.class, "quantity"));
        validation.addValidator(new PartCheckMinimumQuantity());
    }

    /**
     * Minimal constructor for Part
     * 
     * @param quantity
     *            (int)
     */
    public Part(int quantity) {
        super(quantity);
    }

    /**
     * Implements adding single comestible to a collection. The generated superclass forgets to validate the business
     * rules, so we do it here.
     */
    @Override
    public void setComestible(Comestible element) {
        super.setComestible(element);
        super.validation.validate();
    }

}
