
/**
 * Extension point generated initially by Mod4j BusinessDomain DSL by BeanClassExtensionPoint in NewJavaBean.xpt at: Tue Apr 14 13:01:45 CEST 2009
 */
package com.rosa.breakfast.domain;

/**
 * 
 *
 * @author Generated by Mod4j BusinessDomain DSL
 */
public class Part extends PartImplBase {

	/**
	 * Default no-argument constructor for Part 
	 */
	protected Part() {

	}

	/**
	 * Minimal constructor for Part
	 * @param quantity (int) 
	 */
	public Part(int quantity) {
		super(quantity);
	}

}
