<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="DataContractDsl"
    nsURI="http://www.mod4j.org/datacontract" nsPrefix="datacontract">
  <eClassifiers xsi:type="ecore:EClass" name="DataContractModel" eSuperTypes="#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dtos" upperBound="-1" eType="#//Dto"
        containment="true" eOpposite="#//Dto/datacontractModel"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="enumerations" upperBound="-1"
        eType="#//Enumeration" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="businessClasses" upperBound="-1"
        eType="#//BusinessClassReference" containment="true" eOpposite="#//BusinessClassReference/datacontractModel"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Dto" eSuperTypes="#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="datacontractModel" eType="#//DataContractModel"
        eOpposite="#//DataContractModel/dtos"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BusinessClassDto" eSuperTypes="#//Dto">
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
        eType="#//Property" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="base" eType="#//BusinessClassReference"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ListDto" eSuperTypes="#//Dto">
    <eStructuralFeatures xsi:type="ecore:EReference" name="baseDto" eType="#//Dto"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="selectedProperties" upperBound="-1"
        eType="#//PropertyReference"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SubsetDto" eSuperTypes="#//Dto">
    <eStructuralFeatures xsi:type="ecore:EReference" name="baseDto" eType="#//Dto"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="selectedProperties" upperBound="-1"
        eType="#//PropertyReference" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CompositeDto" eSuperTypes="#//Dto">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dtos" upperBound="-1" eType="#//Dto"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReferenceDto" eSuperTypes="#//Dto"/>
  <eClassifiers xsi:type="ecore:EClass" name="Property" eSuperTypes="#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PropertyReference" eSuperTypes="#//Property"/>
  <eClassifiers xsi:type="ecore:EClass" name="DataProperty" eSuperTypes="#//Property"/>
  <eClassifiers xsi:type="ecore:EClass" name="StringProperty" eSuperTypes="#//DataProperty"/>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanProperty" eSuperTypes="#//DataProperty"/>
  <eClassifiers xsi:type="ecore:EClass" name="Enumeration" eSuperTypes="#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="literals" upperBound="-1"
        eType="#//EnumerationLiteral" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EnumerationLiteral"/>
  <eClassifiers xsi:type="ecore:EClass" name="ModelElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CustomDto" eSuperTypes="#//Dto">
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
        eType="#//Property" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BusinessClassReference" eSuperTypes="#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="modelname" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="datacontractModel" eType="#//DataContractModel"
        eOpposite="#//DataContractModel/businessClasses"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntegerProperty" eSuperTypes="#//DataProperty"/>
  <eClassifiers xsi:type="ecore:EClass" name="DecimalProperty" eSuperTypes="#//DataProperty"/>
  <eClassifiers xsi:type="ecore:EClass" name="EnumerationProperty" eSuperTypes="#//DataProperty">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//Enumeration"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DateTimeProperty" eSuperTypes="#//DataProperty"/>
</ecore:EPackage>
