<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="PresentationDsl"
    nsURI="http://www.mod4j.org/pmfmod" nsPrefix="pmfmod">
  <eClassifiers xsi:type="ecore:EClass" name="AssociationRoleReference" eSuperTypes="#//ModelElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="ContentForm" eSuperTypes="#//Form">
    <eStructuralFeatures xsi:type="ecore:EReference" name="formElements" upperBound="-1"
        eType="#//FormElement" containment="true" eOpposite="#//FormElement/form"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actions" upperBound="-1"
        eType="#//Process" containment="true" eOpposite="#//Process/contentForm"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CompoundDialogue" eSuperTypes="#//Dialogue">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dialogues" upperBound="-1"
        eType="#//DialogueCall" containment="true" eOpposite="#//DialogueCall/compoundDialogue"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CollectionDialogue" eSuperTypes="#//CompoundDialogue"/>
  <eClassifiers xsi:type="ecore:EClass" name="DataProperty" eSuperTypes="#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isEnumeration" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="formElement" eType="#//FormElement"
        eOpposite="#//FormElement/dataProperty"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Dialogue" abstract="true" eSuperTypes="#//UIModelElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="readonly" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="processes" upperBound="-1"
        eType="#//ProcessCall" containment="true" eOpposite="#//ProcessCall/owningDialogue"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DialogueCall" eSuperTypes="#//UIModelElementCall">
    <eStructuralFeatures xsi:type="ecore:EReference" name="compoundDialogue" eType="#//CompoundDialogue"
        eOpposite="#//CompoundDialogue/dialogues"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DtoPropertyReference" eSuperTypes="#//ModelElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExternalReference" eSuperTypes="#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="modelName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Form" eSuperTypes="#//Dialogue"/>
  <eClassifiers xsi:type="ecore:EClass" name="FormElement" eSuperTypes="#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="references" eType="#//DtoPropertyReference"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="readonly" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="form" lowerBound="1" eType="#//ContentForm"
        eOpposite="#//ContentForm/formElements"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataProperty" eType="#//DataProperty"
        containment="true" eOpposite="#//DataProperty/formElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MasterDetail" eSuperTypes="#//CompoundDialogue">
    <eStructuralFeatures xsi:type="ecore:EReference" name="master" lowerBound="1"
        eType="#//DialogueCall" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="detail" lowerBound="1"
        eType="#//DialogueCall" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModelElementWithContext" abstract="true"
      eSuperTypes="#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="contextRef" eType="#//ExternalReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="presentationModel" eType="#//PresentationModel"
        eOpposite="#//PresentationModel/elements"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="collectionContext" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModelElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PresentationModel" eSuperTypes="#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//ModelElementWithContext" containment="true" eOpposite="#//ModelElementWithContext/presentationModel"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="externalReferences" upperBound="-1"
        eType="#//ExternalReference" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="start" eType="#//Application"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Process" eSuperTypes="#//UIModelElement">
    <eOperations name="isInteractive" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="processElements" upperBound="-1"
        eType="#//UICall" containment="true" eOpposite="#//UICall/process"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//ProcessType"
        defaultValueLiteral="CUSTOM"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contentForm" eType="#//ContentForm"
        eOpposite="#//ContentForm/actions"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="link" eType="#//AssociationRoleReference"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProcessCall" eSuperTypes="#//UIModelElementCall">
    <eStructuralFeatures xsi:type="ecore:EReference" name="owningDialogue" eType="#//Dialogue"
        eOpposite="#//Dialogue/processes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UIModelElement" abstract="true" eSuperTypes="#//ModelElementWithContext"/>
  <eClassifiers xsi:type="ecore:EClass" name="UIModelElementCall" eSuperTypes="#//UICall">
    <eStructuralFeatures xsi:type="ecore:EReference" name="contextExp" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="arguments" upperBound="-1"
        eType="#//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UICall" abstract="true" eSuperTypes="#//ModelElement">
    <eOperations name="asProcessCall" eType="#//ProcessCall"/>
    <eOperations name="asDialogueCall" eType="#//DialogueCall"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="process" eType="#//Process"
        eOpposite="#//Process/processElements"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="condition" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ProcessType">
    <eLiterals name="NEW"/>
    <eLiterals name="SAVE" value="1"/>
    <eLiterals name="EDIT" value="2"/>
    <eLiterals name="DELETE" value="3" literal="DELETE"/>
    <eLiterals name="CUSTOM" value="4"/>
    <eLiterals name="CANCEL" value="5"/>
    <eLiterals name="ADDTO" value="6"/>
    <eLiterals name="REMOVEFROM" value="7"/>
    <eLiterals name="LINK" value="8"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ServiceExpression" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="serviceName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="serviceMethod" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NavigationExpression" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="references" upperBound="-1"
        eType="#//AssociationRoleReference" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="composition" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expression" eSuperTypes="#//ModelElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="StandardExpression" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//ExpressionType"
        defaultValueLiteral="NONE"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ExpressionType">
    <eLiterals name="ALL"/>
    <eLiterals name="NONE" value="1"/>
    <eLiterals name="FIND" value="2"/>
    <eLiterals name="SELECTION" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OperationExpression" eSuperTypes="#//Expression"/>
  <eClassifiers xsi:type="ecore:EClass" name="Application" eSuperTypes="#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="startProcesses" upperBound="-1"
        eType="#//ProcessCall" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
