<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="PresentationDsl"
    nsURI="http://www.mod4j.org/pmfmod" nsPrefix="pmfmod">
  <eClassifiers xsi:type="ecore:EClass" name="AssociationRoleReference" eSuperTypes="#//NamedReference"/>
  <eClassifiers xsi:type="ecore:EClass" name="AutomatedProcess" eSuperTypes="#//Process"/>
  <eClassifiers xsi:type="ecore:EClass" name="ContentForm" eSuperTypes="#//Form">
    <eStructuralFeatures xsi:type="ecore:EReference" name="formElements" upperBound="-1"
        eType="#//FormElement" containment="true" eOpposite="#//FormElement/form"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CompoundDialogue" eSuperTypes="#//Dialogue">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dialogues" upperBound="-1"
        eType="#//DialogueCall" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CollectionDialogue" eSuperTypes="#//CompoundDialogue"/>
  <eClassifiers xsi:type="ecore:EClass" name="Dialogue" abstract="true" eSuperTypes="#//UIModelElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="readonly" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="processes" upperBound="-1"
        eType="#//ProcessCall" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DialogueCall" abstract="true" eSuperTypes="#//UIModelElementCall"/>
  <eClassifiers xsi:type="ecore:EClass" name="DirectDialogueCall" eSuperTypes="#//DialogueCall"/>
  <eClassifiers xsi:type="ecore:EClass" name="DirectProcessCall" eSuperTypes="#//ProcessCall"/>
  <eClassifiers xsi:type="ecore:EClass" name="DtoPropertyReference" eSuperTypes="#//NamedReference"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExternalReference" eSuperTypes="#//NamedReference">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="modelName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Form" eSuperTypes="#//Dialogue"/>
  <eClassifiers xsi:type="ecore:EClass" name="FormElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="references" eType="#//DtoPropertyReference"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="readonly" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="form" lowerBound="1" eType="#//ContentForm"
        eOpposite="#//ContentForm/formElements"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InteractiveProcess" eSuperTypes="#//Process"/>
  <eClassifiers xsi:type="ecore:EClass" name="Link" abstract="true" eSuperTypes="#//ModelElement">
    <eOperations name="getTarget" eType="#//NamedReference"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LinkedDialogueCall" eSuperTypes="#//DialogueCall">
    <eStructuralFeatures xsi:type="ecore:EReference" name="link" eType="#//LinkRef"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LinkedProcessCall" eSuperTypes="#//ProcessCall">
    <eStructuralFeatures xsi:type="ecore:EReference" name="link" eType="#//LinkRef"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LinkRef" eSuperTypes="#//NamedReference"/>
  <eClassifiers xsi:type="ecore:EClass" name="LinkPath" eSuperTypes="#//Link">
    <eStructuralFeatures xsi:type="ecore:EReference" name="steps" lowerBound="1" upperBound="-1"
        eType="#//LinkRef"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LinkStep" eSuperTypes="#//Link">
    <eStructuralFeatures xsi:type="ecore:EReference" name="reference" eType="#//AssociationRoleReference"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MasterDetail" eSuperTypes="#//CompoundDialogue">
    <eStructuralFeatures xsi:type="ecore:EReference" name="master" lowerBound="1"
        eType="#//DialogueCall" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="detail" lowerBound="1"
        eType="#//DialogueCall" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModelElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contextRef" eType="#//ExternalReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="presentationModel" lowerBound="1"
        eType="#//PresentationModel" eOpposite="#//PresentationModel/elements"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedReference">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PresentationModel">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//ModelElement" containment="true" eOpposite="#//ModelElement/presentationModel"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="externalReferences" upperBound="-1"
        eType="#//ExternalReference" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Process" abstract="true" eSuperTypes="#//UIModelElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="processElements" upperBound="-1"
        eType="#//UICall" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProcessCall" abstract="true" eSuperTypes="#//UIModelElementCall"/>
  <eClassifiers xsi:type="ecore:EClass" name="UIModelElement" abstract="true" eSuperTypes="#//ModelElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="UIModelElementCall" eSuperTypes="#//UICall">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="alias" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UICall" abstract="true" eSuperTypes="#//NamedReference"/>
</ecore:EPackage>
