/**
 * Extension Point initial generated at: Wed Jun 18 08:52:21 CEST 2008
 */
package org.company.recordshop.domain;

/**
 * 
 *
 * @author Generated by Mod4j BusinessDomain DSL
 */
public class Product extends ProductImplBase {

	/**
	 * Default no-argument constructor for Product 
	 */
	protected Product() {

	}

	/**
	 * Minimal constructor for Product
	 * @param productNumnber (string) 
	 * @param price (integer) 
	 */
	public Product(String productNumnber, int price) {
		super(productNumnber, price);
	}

}
