/*
 * generated by Xtext
 */
package org.mod4j.dsl.service.xtext;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ServiceRuntimeModule extends org.mod4j.dsl.service.xtext.AbstractServiceRuntimeModule {

	// contributed by org.eclipse.xtext.generator.validation.CheckFragment
	@Override
	@org.eclipse.xtext.service.SingletonBinding(eager=true)	public Class<? extends org.mod4j.dsl.service.xtext.validation.ServiceCheckValidator> bindServiceCheckValidator() {
		return org.mod4j.dsl.service.xtext.validation.MyServiceCheckValidator.class;
	}

}
