/*
* generated by Xtext
*/
package org.mod4j.dsl.datacontract.xtext.outline;

import org.eclipse.xtext.ui.common.editor.outline.transformer.AbstractDeclarativeSemanticModelTransformer;

/**
 * customization of the default outline structure
 * 
 */
public class DataContractTransformer extends AbstractDeclarativeSemanticModelTransformer {
	
}
