/** 
 * Initial generated by Mod4j at Wed Jun 18 08:52:21 CEST 2008
 */
package org.company.recordshop.data.spring.dao;

/**
 * OrderLineDao Data Access Object (DAO). Responsible for accessing the database.
 *
 * This interface is intended to be manually changed by developers. 
 * 
 * @author Initial generated by Mod4j
 * 
 */
public interface OrderLineDao extends OrderLineDaoBase {

	// TODO: Add manual DAO methods over here
}
