
/**
 * Initially generated by Mod4j at Wed Apr 08 15:31:19 CEST 2009
 */
package com.rosa.breakfast.data.hibernate.spring;

import com.rosa.breakfast.data.AddressDao;

/**
 * Address Data Access Object (DOA) Implementation. Responsible for Creating,
 * Reading, Updating and Deleting Address objects in the database. All database
 * access is done here.
 *  
 * @author Initially generated by Mod4j
 */
public class AddressDaoImpl extends AddressDaoImplBase implements AddressDao {


}
