
/**
 * Initially generated by Mod4j at Wed Apr 08 11:05:51 CEST 2009
 */
package com.rosa.breakfast.data.hibernate.spring;

import com.rosa.breakfast.data.BreakfastOrderDao;

/**
 * BreakfastOrder Data Access Object (DOA) Implementation. Responsible for Creating,
 * Reading, Updating and Deleting BreakfastOrder objects in the database. All database
 * access is done here.
 *  
 * @author Initially generated by Mod4j
 */
public class BreakfastOrderDaoImpl extends BreakfastOrderDaoImplBase
		implements
			BreakfastOrderDao {

}
