
/**
 * Initially generated by Mod4j at Wed Apr 01 21:03:34 CEST 2009
 */
package com.rosa.breakfast.data.hibernate.spring;

import com.rosa.breakfast.data.StandardBreakfastDao;

/**
 * StandardBreakfast Data Access Object (DOA) Implementation. Responsible for Creating,
 * Reading, Updating and Deleting StandardBreakfast objects in the database. All database
 * access is done here.
 *  
 * @author Initially generated by Mod4j
 */
public class StandardBreakfastDaoImpl extends StandardBreakfastDaoImplBase
		implements
			StandardBreakfastDao {

}
