
/**
 * Extension point, initially generated by Mod4j. 
 *     Time             : Sat Sep 25 17:39:28 CEST 2010
 *     Application model: TestSVC
 *     Generator        :  Mod4j ServiceDsl generator: LocalServiceImpl.xpt
 *
 * It is intended to customize and maintain this file by hand. 
 * If you remove this file, it will be regenerated by Mod4j to its original state.
 */

package org.company.recordshop.service;

import java.util.List;

import org.company.recordshop.service.TestSVCLocalServiceImplBase;
import org.company.recordshop.service.dto.DerivedDto;

import org.company.recordshop.service.dto.translators.DerivedDtoTranslator;
import org.company.recordshop.domain.Derived;

/**
 * @author Initially generated by Mod4j
 */
public class TestSVCLocalServiceImpl extends TestSVCLocalServiceImplBase {

}
