/**
 * Extension point, initially generated by Mod4j. 
 *     Time             : Fri Sep 25 15:56:52 CEST 2009
 *     Application model: TestSVC
 *     Generator        :  Mod4j ServiceDsl generator: LocalServiceImpl.xpt
 *
 * It is intended to customize and maintain this file by hand. 
 * If you remove this file, it will be regenerated by Mod4j.
 */
package org.company.recordshop.service;

import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import org.company.recordshop.business.TestSVCDomainService;
import org.company.recordshop.service.TestSVCLocalServiceImplBase;
import org.company.recordshop.service.dto.DerivedDto;

import org.company.recordshop.service.dto.translators.DerivedDtoTranslator;
import org.company.recordshop.domain.Derived;

/**
 * @author Initially generated by Mod4j
 */
@Component
public class TestSVCLocalServiceImpl extends TestSVCLocalServiceImplBase {
    @Autowired
    public TestSVCLocalServiceImpl(
            final TestSVCDomainService testSVCDomainService,
            final DerivedDtoTranslator derivedDtoTranslator) {
        super(testSVCDomainService, derivedDtoTranslator);
    }
}
