
/**
 * Generated by Mod4j Service DSL: BusinessService::BusinessService at: Wed Apr 01 21:03:33 CEST 2009
 * from model breakfast
 */
package com.rosa.breakfast.business;

/**
 * @author Generated by Mod4j
 */
public interface BreakfastDomainService extends BreakfastDomainServiceBase {

	public boolean isComestibleUsed(Long id);
	
}
