/**
 * Generated by Mod4j Service DSL: BusinessService::BusinessService at: Sat Dec 06 14:27:01 CET 2008
 * from model CustomerServiceModel
 */
package org.company.recordshop.business;

/**
 * @author Generated by Mod4j
 */
public interface CustomerServiceModelDomainService
		extends
			CustomerServiceModelDomainServiceBase {

	// TODO MOD4J Generate custom methods?

	// TODO MOD4J Generate custom methods?

	// TODO MOD4J Generate custom methods?

}
