/**
 * Generated by Mod4j Service DSL: BusinessServiceImpl::BusinessServiceImpl at: Tue Feb 10 13:56:29 CET 2009
 * from model OrderServiceModel
 */
package org.company.recordshop.business;

import org.company.recordshop.domain.Order;
import org.company.recordshop.data.spring.dao.OrderDao;
import org.company.recordshop.domain.Customer;
import org.company.recordshop.data.spring.dao.CustomerDao;

/**
 * @author Generated by Mod4j, use as extension point to implement custom business services
 */
public class OrderServiceModelDomainServiceImpl
		extends
			OrderServiceModelDomainServiceImplBase
		implements
			OrderServiceModelDomainService {

}
