/**
 * Extension point, initially generated by Mod4j. 
 *     Time             : Fri Sep 25 13:14:53 CEST 2009
 *     Application model: TestSVC
 *     Generator        :  Mod4j ServiceDsl generator: BusinessService.xpt
 *
 * It is intended to customize and maintain this file by hand. 
 * If you remove this file, it will be regenerated by Mod4j.
 */
/**
 * Generated by Mod4j Service DSL: BusinessService::BusinessService at: Fri Sep 25 13:14:53 CEST 2009
 * from model TestSVC
 */
package org.company.recordshop.business;

/**
 * @author Generated by Mod4j
 */
public interface TestSVCDomainService extends TestSVCDomainServiceBase {
}
